version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: vehicle_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Yokona@76
      MYSQL_DATABASE: vehicle_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - vehicle_net

  app:
    build: .
    container_name: vehicle_rpa_app
    depends_on:
      - db
    networks:
      - vehicle_net

volumes:
  db_data:

networks:
  vehicle_net:
