version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: car_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Yokona@76
      MYSQL_DATABASE: vehicle_db
    ports:
      - "3308:3306"
    volumes:
      - car_mysql_data:/var/lib/mysql

  scraper:
    build: .
    container_name: car_scraper
    depends_on:
      - mysql
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    networks:
      - car_network

volumes:
  car_mysql_data:

networks:
  car_network:
    driver: bridge
